// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgdxZjnXSzITmMFy5Zmv4J_6iNvuMpeXc',
    appId: '1:948140389448:web:834a89d6af3a10e189d47d',
    messagingSenderId: '948140389448',
    projectId: 'quiklerider-22552',
    authDomain: 'quiklerider-22552.firebaseapp.com',
    storageBucket: 'quiklerider-22552.firebasestorage.app',
    measurementId: 'G-ZJ98JP92WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-6w9TFkbTRzefAyR7uUidqVLG_AODC_w',
    appId: '1:948140389448:android:18e941c3474003ac89d47d',
    messagingSenderId: '948140389448',
    projectId: 'quiklerider-22552',
    storageBucket: 'quiklerider-22552.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBHh8pgXHxwcr6uUmNbiVNvNNbyzg97b8',
    appId: '1:948140389448:ios:3dcf97deae2230b789d47d',
    messagingSenderId: '948140389448',
    projectId: 'quiklerider-22552',
    storageBucket: 'quiklerider-22552.firebasestorage.app',
    iosBundleId: 'com.quikle.quikleuser',
  );

}