name: Quickle User Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Setup Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Run code generation
      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # 5. Build Android APK
      - name: Build APK
        run: flutter build apk --release

      # 6. Build iOS (unsigned, no codesign)
      - name: Build iOS
        run: flutter build ios --release --no-codesign

      # 7. Package unsigned iOS IPA
      - name: Package unsigned iOS IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r unsigned-app.ipa Payload

      # 8. Upload Android APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: quickle_user-app-release
          path: build/app/outputs/flutter-apk/**/*.apk

      # 9. Upload iOS IPA as artifact
      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: quickle_user-ios-ipa
          path: build/ios/iphoneos/unsigned-app.ipa

      # 10. Publish GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.${{ github.run_number }}
          name: "Quickle User Release v1.${{ github.run_number }}"
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/ios/iphoneos/unsigned-app.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
